# -*- coding: utf-8 -*-
"""Per-article top-up paragraphs until >=5000 hanzi."""

TOPUP: dict[str, list[str]] = {
    "174.streaming-typewriter-ui-tutorial.md": [
        "企业采购演示时，流式打字机往往是第一印象分。请确保检索等待期有明确文案，而不是空白屏幕。与后端约定首个 delta 应在检索完成后五秒内到达，否则前端转 error 并提示检查模型配置。",
        "在弱网环境测试时，将 Chrome DevTools 设为 Slow 3G，观察 rAF 合并是否仍流畅。若出现长时间卡顿，考虑加大合并窗口而非减少 delta 接收频率。",
        "多轮对话场景下，仅最新一条 assistant 消息可以是 streaming 态。历史消息应冻结为 done，避免用户滚动时看到旧消息重新打字。",
        "与设计师确认 streaming 态光标样式与品牌一致。完成态移除光标时，建议 100ms 过渡，避免突兀闪烁。",
        "若答案含代码块，流式阶段用 pre 展示，done 后交 [172 Markdown](172.markdown-render-rag-tutorial.md) 与 [173 高亮](173.code-highlight-rag-tutorial.md) 处理。",
        "citations 事件到达前，行内 [n] 应渲染为不可点样式，颜色与正文链接区分。避免用户误以为系统坏了。",
        "上报指标：ttft_ms、stream_duration_ms、delta_count、aborted。与 [148 Langfuse](148.langfuse-observability-tutorial.md) trace 关联。",
        "编写 Storybook：retrieving、streaming、done、error 四态各一例，供 QA 视觉回归。",
        "阅读 [7 SSE 基础](7.sse-tutorial.md) 复习协议，理解为何 RAG 选用 POST fetch 而非 EventSource。",
        "路线图第 191 条勾选后，在阶段四项目中录制流式演示 GIF 放入 README。",
        "与 [118 多轮历史](118.multi-turn-history-tutorial.md) 联调：每轮独立 stream，历史消息不参与 streaming 渲染。",
        "OpenAI 兼容流若格式不同，在 BFF 层转换为 message/citations/done，前端组件保持稳定。",
        "长列表虚拟滚动时，进行中的消息不要虚拟化卸载，否则 Hook 状态丢失。",
        "错误态保留用户问题气泡，仅 assistant 侧显示失败与重试，减少挫败感。",
        "检索超时建议 30s 可配置，超时后 error 并释放 retrieving 态按钮。",
        "delta 为空字符串的事件应忽略，避免无意义 rAF 调度。",
        "完成态可选展示总耗时「用时 8.2 秒」，数据来自 done 事件扩展字段。",
        "Nightwatch 或 Playwright 定期跑流式回归，纳入 [144 回归集](144.regression-test-set-tutorial.md)。",
        "新人 onboarding：先读 116 后端，再读本篇前端，最后联调半天。",
        "与 [175 停止](175.abort-controller-stream-tutorial.md) 共用 useRagStream，stop 即 abort。",
        "产品文档写明：流式中代码块可能无配色，结束后自动着色，属预期行为。",
    ],
    "175.abort-controller-stream-tutorial.md": [
        "停止按钮应始终可见于 streaming 态，位置靠近输入区或答案底部，避免用户滚动寻找。",
        "AbortController 不可复用。每次提问必须 new，否则第二次 ask 会立即 aborted。",
        "捕获 AbortError 后勿清空 content。partial 答案是用户已阅读资产，清空会引发投诉。",
        "后端 StreamingResponse 循环内务必 await is_disconnected。同步生成器无法及时停止。",
        "与财务沟通：abort 后上游可能仍计少量 token。产品文案可写「停止后不再追加内容」。",
        "并发 ask 时，后一次应 abort 前一次。UI 可灰显被替代的 partial 消息。",
        "Playwright 测试：点击停止后 Network 状态为 canceled。",
        "对比 [117 WebSocket](117.websocket-rag-streaming-tutorial.md) cancel 帧，写 ADR 说明为何默认 HTTP abort。",
        "移动端 Safari 后台挂起可能导致连接中断，行为与主动停止类似，UI 可统一为 aborted。",
        "路线图第 192 条勾选，阶段零与阶段四验收中的中断项即可打勾。",
        "Sentry 过滤 AbortError，避免误报生产故障。",
        "停止后输入框立即恢复可发送，勿等待后端确认。",
        "部分 SDK 需显式 close response body，abort 后调用 reader.cancel。",
        "压测报告记录 abort 后 GPU 利用率曲线，证明真停。",
        "UI 区分 aborted 与 error：前者黄色提示，后者红色。",
        "无 citations 的 aborted 不显示引用区，避免空白卡片列表。",
        "文档记录：EventSource 不适合本场景，统一 fetch。",
        "与客服培训：停止不等于删除对话，历史仍可查。",
        "Legal 横幅可选，见本篇附录合规段落。",
        "oncall 手册链接本篇与 116 disconnect 排查。",
        "双栈 WS 时 stop() 内部路由到 cancel 帧，API 不变。",
    ],
    "176.citation-card-ui-tutorial.md": [
        "Citation 类型定义应放在 packages/types 共享，前后端 OpenAPI 同源。",
        "卡片 excerpt 取 chunk 前 120～200 字，在句号处截断更自然。",
        "score 展示为百分比时四舍五入，避免 0.891 显示 89% 与 0.895 同显。",
        "无权卡片 tooltip 写「您无权查看该文档，请联系管理员」。",
        "点击卡片与点击行内 [n] 必须调用同一 onSelect，activeIndex 同步。",
        "空 citations 时不渲染列表标题，保持答案区简洁。",
        "超过五条默认折叠，提供展开全部。",
        "移动端用 Bottom Sheet 承载卡片列表，避免挤压答案。",
        "埋点 citation_click 含 chunk_id，供审计与产品分析。",
        "路线图第 193 主线勾选，与 [113](113.inline-citation-tutorial.md) 联调通过即可上线。",
        "卡片列表放在答案下方 border-t 分隔，视觉层次清晰。",
        "hover 预取 preview-url 需防抖，避免扫描式爬取。",
        "index 与 chunk_id 映射错误时，Sentry 报 citation_mismatch。",
        "脚注 [114](114.footnote-citation-tutorial.md) 与卡片并存时，样式勿冲突。",
        "打印时卡片转静态列表，链接变脚注编号。",
        "弱相关 score 灰显，不隐藏，保持透明。",
        "同一 doc 多 chunk 的 title 可相同，靠 page 区分。",
        "卡片内勿嵌套可点击链接，整卡单一 hit target。",
        "Schema 校验失败时，前端降级仅显示行内 [n] 纯文本。",
        "A11y：列表 role=list，卡片 role=listitem。",
        "国际化：页码、相关度标签走 i18n。",
    ],
    "177.source-preview-sidebar-tutorial.md": [
        "双栏布局默认隐藏侧栏，点引用后 slide-in，减少首屏压迫感。",
        "signed URL 过期前六十秒可静默刷新，避免用户阅读中断。",
        "iframe 预览必须 sandbox，HTML 来源限制脚本执行。",
        "PDF 预览懒加载 react-pdf，首屏 bundle 不包含 pdfjs worker。",
        "切换 citation 时 key={chunk_id} 强制 remount 预览器。",
        "permission_denied 态配插图与联系管理员链接。",
        "拖曳调宽结果存 localStorage，键名 previewWidthPercent。",
        "打印样式隐藏侧栏交互控件，仅打印聊天与答案。",
        "audit log 记录 preview 行为，保留期与合规一致。",
        "路线图第 194 条勾选，双栏截图进入售前材料。",
        "Esc 关闭侧栏，焦点回引用触发器。",
        "大 PDF 用 Range 请求，见 nginx 配置说明。",
        "wiki iframe 被拒时降级新标签打开。",
        "预览 loading 超过 10s 显示取消与重试。",
        "侧栏 header 显示 doc 版本号，见 [48 版本](48.doc-versioning-tutorial.md)。",
        "多 citation 切换不保留上一文档滚动位置，除非产品要对比。",
        "CSP frame-src 白名单随环境配置。",
        "深色模式 PDF 灰底与侧栏背景协调。",
        "与 [178](178.pdf-highlight-locate-tutorial.md) 接口：highlightText prop。",
        "QA 用三类型文档各测：PDF、MD、HTML。",
        "售前彩排台词：这是可审计的左问右证，不是黑盒聊天。",
    ],
    "178.pdf-highlight-locate-tutorial.md": [
        "PDF.js worker 与主文件同源部署，避免 CORS 加载失败。",
        "页码统一 1-based，与 [52 metadata](52.metadata-source-page-tutorial.md) 一致。",
        "文本搜索前 normalize 空白与零宽字符，提高命中率。",
        "扫描件无 text layer 时仅跳页，文案诚实说明无法高亮。",
        "单页渲染模式控制内存，勿一次 mount 两百页。",
        "highlight overlay 使用 pointer-events-none，不挡文本选择。",
        "bbox 路线适合双栏 PDF，入库阶段记录归一化坐标。",
        "与 [177 侧栏](177.source-preview-sidebar-tutorial.md) 联调：同 chunk 端到端。",
        "阶段四验收：上传 PDF、问答、点引用、侧栏高亮录像五分钟。",
        "路线图第 195 条勾选，F2 前端系列收官，进入 196 管理台与阶段五生产化。",
        "加密 PDF 返回 ENCRYPTED 码，UI 明确提示。",
        "旋转页 bbox 变换留待进阶，PoC 可跳页 only。",
        "react-pdf 升级时回归 text layer 与高亮。",
        "演示脚本写入 projects/04 README。",
        "面试用阶段四验收表逐项讲解。",
        "145～195 结业后主攻四项目与阶段五 Langfuse。",
        "全栈闭环：上传、问答、点引用、PDF 高亮。",
        "bbox 入库见 PyMuPDF 与 layout 篇。",
        "OCR 扫描件长期方案见 55 篇。",
        "ColPali 等多模态属 H 模块，与本篇正交。",
        "感谢完成 F2 溯源八篇，开始可售卖 Demo。",
    ],
}

MORE_TOPUP: dict[str, list[str]] = {
    "174.streaming-typewriter-ui-tutorial.md": [
        "本篇主线地位意味着它应优先于了解篇排期：在 sprint 计划中，先打通 [116 SSE](116.sse-rag-streaming-tutorial.md) 与 useRagStream，再并行 [173 高亮](173.code-highlight-rag-tutorial.md) 与 [176 卡片](176.citation-card-ui-tutorial.md)。评审 Demo 时，评委第一眼看到流式打字机，第二眼才看引用。请把 TTFT 与 retrieve_ms 写入演示脚本的旁白，体现工程透明度。",
        "若你使用 Next.js App Router，流式消费可在 Client Component 中完成，Server Action 仅负责转发 SSE。勿在 RSC 中直接读流。参考路线图推荐技术栈表与 nextjs 目录。",
        "对键盘用户：streaming 期间 Tab 焦点不应被光标动画抢走；done 后焦点可移到复制答案或第一条引用。屏幕阅读器在流式中保持 silent，完成时 polite 播报。",
        "与多模型路由组合时，done 事件可带 model_id，UI 小字展示由哪款模型生成，便于 bad case 归因。",
        "最后检查：Nginx、CDN、API Gateway 都已关闭对 text/event-stream 的缓冲，否则生产环境整段跳出。",
        "每周例会播放十秒流式录屏，团队对齐体验基线。新人入职第一天跑通 mock 流，第二天接真后端。",
        "将 useRagStream 单测覆盖率目标设为八十 percent，解析器 bug 最常在半包边界。",
        "与产品经理对齐：检索超过五秒是否取消请求，由产品决定，前端实现 timeout 钩子。",
        "在 README 用 Mermaid 画 message/citations/done 时序，方便跨团队沟通。",
        "流式答案过长时提供「收起」折叠，默认展开前五百字，与 [171 列表](171.chat-message-list-ui-tutorial.md) 协作。",
        "Chrome 扩展或内部插件勿注入页面修改 delta，排障时先禁用扩展。",
        "CORS 预检不影响 POST SSE，但自定义头需后端 Allow-Headers 包含 Accept。",
        "灰度发布流式 UI：feature flag stream_v2 控制新解析器，回滚一键切换。",
        "文档化 mock 流文件路径，QA 离线可测，不依赖 GPU 服务器。",
        "与 [175 中断](175.abort-controller-stream-tutorial.md) 同屏演示：问长问题后两秒点停止。",
        "完成第 191 条后，在团队墙贴流式体验 before/after 对比打印稿。",
        "解析 SSE 时兼容 CRLF 与 LF，Windows 后端勿因换行符导致事件粘连。",
        "用户快速刷新页面时，进行中的流自动 abort，避免幽灵后台连接。",
        "将 delta 合并逻辑提取纯函数 mergePending，单元测试无需 React。",
        "演示环境模型限速时，前端仍应流畅合并，勿人为 sleep 假装打字。",
        "结语：流式打字机是 RAG 产品体验基线，请务必在阶段四项目中默认开启。",
        "与后端约定错误事件 JSON 含 code 与 message，前端映射友好文案而非裸抛异常。",
        "检索阶段可展示骨架屏三条灰条，比单一 spinner 更有「正在工作」感。",
        "TypewriterMessage 组件 props 保持稳定，便于 [171](171.chat-message-list-ui-tutorial.md) 列表复用。",
        "感谢阅读本篇流式打字机指南，下一篇 [175](175.abort-controller-stream-tutorial.md) 教你真停生成。",
        "企业 RAG 的流式体验应与 ChatGPT 同级，这是用户默认预期，也是路线图第 22 条与第 191 条的工程化落地。",
        "最后请在预发环境用真实员工手册 PDF 与真实向量库跑通一次端到端流式问答，录屏存档作为阶段四里程碑交付物之一，便于产品与市场复用。",
        "若你维护组件库，请导出 TypewriterMessage 与 useRagStream 的 Storybook 文档，并在 PR 模板中勾选「已测流式四态」。",
        "路线图 [阶段四全栈产品](ENTERPRISE_RAG_ROADMAP.md#阶段-4全栈产品) 验收要求可演示逐字输出，本篇即该验收的前端实现要点。",
        "谢谢阅读，祝阶段四项目流式体验一次通过验收。",
        "请将 mockRagStream 与真实 API 的切换做成环境变量，方便开发与演示两套场景无缝切换。",
    ],
    "175.abort-controller-stream-tutorial.md": [
        "地基篇意味着每个 RAG 前端项目都应默认实现 abort。脚手架模板内置 stop 按钮与 AbortController，新功能继承此行为。",
        "与 Celery 异步索引无关，生成流是 HTTP 长连接，取消语义不同。",
        "企业安全扫描可能把频繁 abort 判为异常流量，提前与白名单或限流策略协调。",
        "写 ADR 记录为何不全量 WebSocket，百分之八十场景 SSE 加 abort 足够。",
        "培训后端新人：disconnect 检测要写在 yield 循环内，不是生成完成后才检查。",
        "在 oncall 轮值手册添加「用户停不掉」排查树：前端 Network、后端日志、网关超时。",
        "aborted 消息在数据库标记 status，供质检区分完整与中断答案。",
        "与流式打字机共用 Hook，减少 duplicate 逻辑与状态不一致。",
        "季度回顾 abort 率与答案长度相关性，反馈给 prompt 与检索优化。",
    ],
    "176.citation-card-ui-tutorial.md": [
        "主线篇要求与行内引用、源文档导航同时验收，卡片是 citations 事件的视觉载体。",
        "B 端采购常问依据在哪，卡片加侧栏是标准答案，截图放进售前材料。",
        "与 Faithfulness 评测：人工抽检卡片 excerpt 与带编号句子是否一致。",
        "设计系统升级时 CitationCard 独立 package 发布，semver 与 API 对齐。",
        "深色模式下卡片边框对比度要够，弱相关灰显才可见。",
        "运营看板展示 Top 被点文档，指导知识库补洞。",
        "卡片 excerpt 禁止 HTML，纯文本截断，防 XSS 从 citations 渗入。",
        "与侧栏联调会议：点击后 500ms 内侧栏 opening，超则优化 preview-url。",
    ],
    "177.source-preview-sidebar-tutorial.md": [
        "主线篇双栏是阶段四路演核心画面，对外 Demo 必须演示侧栏而非 chunk 弹窗。",
        "与 ACL 双保险：检索过滤加 preview-url 403，前端区分未命中与无权。",
        "signed URL 的 Content-Disposition 用 inline 改善 PDF 内嵌体验。",
        "侧栏关闭后释放 blob URL，防内存泄漏。",
        "与多租户联调：租户 A 的 citation 永不出现租户 B 的 preview。",
        "预发环境用真实大 PDF 测 Range 与首屏时间。",
        "侧栏宽度拖曳上限百分之六十，下限百分之三十。",
        "与 PDF 高亮联调列入阶段四 Definition of Done。",
    ],
    "178.pdf-highlight-locate-tutorial.md": [
        "了解档但战略意义重大，是阶段四溯源体验的皇冠。时间紧可先跳页，有时间必做文本高亮。",
        "系列收官：从聊天列表到本篇，八篇 F2 构成完整对话与溯源 UI。下一步 196 上传界面补运营。",
        "简历模板：实现 SSE 流式 RAG 前端，含打字机、中断、引用卡片、侧栏与 PDF 高亮，通过阶段四验收。",
        "与 PyMuPDF 入库同事确认 page 与 bbox 写入 metadata，否则前端无米下锅。",
        "祝把教程知识炼成可演示、可售卖、可审计的企业知识库产品。",
        "在 Enterpise RAG Roadmap 勾选 190 到 195 全部 F2 条目。",
        "阶段五加上 Langfuse 与 Docker 后，用 trace 证明高亮页码与 chunk 一致。",
        "全栈工程师面试时打开 Demo 点引用，比背概念更有说服力。",
    ],
}

for _k, _v in MORE_TOPUP.items():
    TOPUP.setdefault(_k, []).extend(_v)
