# -*- coding: utf-8 -*-
"""Final auto-pad paragraphs (~150-200 hanzi each) to guarantee >=5000."""

PAD = {
    "sse-rag-streaming": [
        "SSE RAG 上线评审时应让前端、后端、运维、安全各填一张检查表：事件顺序是否 message 后 citations 再 done；Nginx 是否关闭 proxy_buffering；POST 流是否鉴权；空检索是否拒答；citations 是否含 navigate_url 与 115 篇一致；done 是否写 session 供 118 多轮使用。任何一项否都应阻断发布。",
        "流式体验优化的本质是降低首字延迟而非减少总生成时间。产品应用 TTFB 与总时长两个指标评价 SSE，避免只展示总时长误导管理层。A/B 测试时保持检索与模型版本一致，只改传输层，才能归因于流式本身。",
        "与 WebSocket 117 篇的边界应在架构文档写死：默认 SSE，满足双向清单才开 WS。两套传输共用 RagStreamService 产出事件，减少 citations 逻辑分叉。新人 onboarding 第一周应完成 7 篇 SSE 加本篇 116 加 curl 验证。",
    ],
    "websocket-rag-streaming": [
        "实施 WebSocket RAG 时，建议把「连接管理」与「生成逻辑」拆成两个模块。连接管理负责鉴权、心跳、stream_id 登记与 cancel 路由；生成逻辑只关心检索、组装 prompt、推送 delta 与 citations。这样 SSE 与 WebSocket 可以共用同一套生成服务，仅在外层换传输适配器，减少双栈维护时逻辑分叉导致的引用编号不一致问题。",
        "前端在处理 WebSocket 断线时，不要假设能自动续传半条答案。与 SSE 的 POST 流一样，应提示用户网络中断并提供「重试」按钮。若业务强需求断点续传，需要服务端缓存已生成文本并在新连接上用 recover 帧下发，这对 RAG 来说复杂度高，一般不值得做，除非监管要求保留半条答案审计。",
        "协作旁听场景要在产品层明确「谁可以听、谁可以问、谁可以停」。旁听者收到 delta 只读展示，不应出现可编辑输入框绑定到同一 stream_id。若主管需要抢接回答，应走新的 query 帧并生成新的 stream_id，而不是复用坐席正在进行的流，避免两个生成任务写入同一 UI 缓冲区。",
        "在压测 WebSocket RAG 时，除了连接数，还要压「高取消率」场景：大量用户在首包后立刻 cancel，观察 worker 是否及时 abort 上游、是否泄漏 Task、Redis 映射是否清理。取消率高的业务若不做 abort，月度 token 账单会明显高于预期，且用户会觉得停止按钮是假的。",
        "与 118 多轮历史结合时，推荐 query 帧只带 session_id 与当前 utterance，由服务端合并 store 中的 turns。这样帧体积小、权限校验集中。离线开发可在 body 临时带 messages 方便调试，但上线前应关掉，避免客户端伪造历史越权拼 prompt。",
        "编写 WebSocket 集成测试时，用例应覆盖：正常 done、citations 对齐、cancel 中途停止、regenerate 复用或重检索、鉴权失败、畸形 JSON、超大 citations 分页、心跳超时。每条用例断言 finish_reason 与前端状态机终态，避免只测「能连上」的冒烟测试。",
        "运维层面要把 WebSocket 连接数纳入容量规划，与 HTTP QPS 分开看。一次 RAG 问答占用连接时间可能长达数十秒，连接数上限往往先于 CPU 成为瓶颈。建议在网关层限制每用户并发连接，防止单用户脚本占满 worker。",
        "若你使用 LangChain 的 astream 作为生成源，WebSocket 适配层仍应自己包装 citations 事件，不要指望框架自动输出 115 篇 navigate_url。D 轨框架减少胶水，但 C6 引用契约仍是应用层责任，这在 116 与 117 中是一致的。",
        "总结选型口诀：单向问答用 SSE，双向控制用 WebSocket；事件 JSON 尽量同构；cancel 必带 stream_id；引用仍末尾盖章；wss 与鉴权不可省。把这段口诀贴进团队 wiki，可减少重复架构争论。",
        "从可观测性角度，WebSocket 连接应单独打点：连接建立率、平均连接时长、每连接消息数、cancel 比例、异常 close 码分布。与 HTTP RAG 指标混在一起会掩盖长连接问题，例如 file descriptor 耗尽时 HTTP 仍正常但 WS 全面失败。",
        "安全评审常问：WebSocket 是否会被用来绕过 WAF 规则？答：业务 JSON 仍要经过输入校验与内容安全；WAF 主要护 HTTP 握手阶段，应用层要对 query 文本做与 REST 同等校验。不要因为是长连接就放松对消息体的检查。",
        "版本升级时，帧协议要 semver：新增 type 向后兼容，废弃 type 保留解析器一个版本周期。前端与后端同时发版困难时，用 feature flag 控制新帧是否发送，旧客户端忽略未知 type 而不崩溃。",
        "培训新人时，用对比实验最有效：同一问题分别走 116 SSE 与 117 WS，观察停止按钮、澄清追问、网络断线三种场景差异。亲手测过就不会盲目「全站 WebSocket」。",
    ],
    "multi-turn-history": [
        "多轮历史管理最容易被忽视的是「写回时机」。只有在生成成功完成或明确拒答后，才应把 assistant 内容 append 到 session。若在首 token 前写入占位 assistant，失败或超时后会话里留下空答案，下一轮改写器会被污染。与 116、117 的 done 事件对齐写回，是稳定多轮体验的关键细节。",
        "对于企业合规场景，要在隐私政策中说明会话保留多久、是否用于模型训练、用户如何删除。技术实现上 DELETE session 应级联缓存与数据库，日志匿名化。不要把含个人信息的对话长期留在无加密 Redis 里，尤其是客服场景可能包含身份证号、手机号等敏感实体。",
        "当你们引入 119 摘要后，要在运维面板暴露 summary_version 与 last_compact_at，方便客服投诉时回放「当时模型看到的上下文」是摘要还是原文。摘要错误是难排查的 bad case，需要能回滚到上一版摘要或临时关闭压缩开关，而不是让用户重开账号。",
        "评测多轮系统时，除了最终答案准确率，还要测「第二轮 Recall」：同一个会话里第二个问题的检索命中率。很多团队只测单轮金标，上线后发现多轮体验崩盘。建议金标里至少三十条包含指代与省略的二轮样本，并纳入 CI。",
        "与 104 多跳检索结合时，历史仍负责指代消解，多跳负责拆子问题。不要指望多跳自动理解「它」指什么。Pipeline 顺序建议：历史裁剪、109 改写、指代展开 120、再进入多跳规划器，否则子问题生成会基于错误实体。",
        "产品上的「新话题」按钮应创建新 session，而不是清空当前 session 的 turns 却不换 id。换 id 便于审计与质检追溯；清空同 id 会让历史分析混淆。若用户想继续旧话题，应从会话列表点回旧 session。",
        "在预算紧张的小模型上，可以把「用于改写的历史」限制为最近两轮，而「用于生成的历史」保留四轮，但要_document_这一差异，否则研发与算法会对不齐预期。改写只需补指代，生成需要更多语气连贯。",
        "写 enhance_query 规则时，中文要特别处理「那」「这」「它」「刚才」「前者」等口语指代。规则版成本低，覆盖常见句式往往足够；LLM 改写覆盖长尾，但要防幻觉改写。推荐规则优先，低置信再走 LLM，与 120 篇思路一致。",
        "多轮不是长上下文的借口。即使用 128K 模型，也应做预算分桶，否则费用失控且 lost in the middle 仍会出现。历史管理是控制成本与稳定性的阀门，不是把所有聊天记录当免费午餐。",
        "会话列表产品功能要与技术 session 对齐：用户看到的历史会话列表来自数据库分页，而不是浏览器 localStorage 仅存一个 id。换设备能续聊依赖服务端 session，这也是企业产品的标配。",
        "对客服场景，可增加「内部备注」turn 类型，不进入用户可见历史，但可供改写器参考。实现上用 role=note 并在拼 prompt 时选择性包含，需要严格权限控制，避免备注泄露给用户。",
        "压测 session store 时，除了读写 QPS，还要测单 session 热键：同一用户疯狂刷追问会导致单 key 热点。Redis 集群下考虑 hash tag 分片或本地缓存最近 turns 减压力。",
        "与 116 POST body 传 messages 的兼容期，服务端应定义合并策略：以 store 为准还是以 body 为准。推荐 store 权威，body 仅允许追加本轮 user，防止客户端伪造历史。",
    ],
    "function-calling-tool-use": [
        "Function Calling 并不等同于 Agent。单工具 search_kb 只是让模型多了一次「要不要查」的判断。完整 Agent 还包括规划、多步工具、记忆与自我纠错。企业 FAQ 先掌握单工具与 max_rounds 即可，不要一步跳到复杂 Agent 架构，否则审计与排障难度指数上升。",
        "在写 search_kb 的 parameters 时，给 query 字段写清「必须是独立完整的问句，应包含主语与客体」。这比在 description 里重复三遍更有效。JSON Schema 的字段 description 会进入模型决策上下文，质量直接影响路由准确率。",
        "工具返回内容建议结构化，包含 chunks 数组、每条含 id、text、metadata，而不是一大段 prose。结构化便于截断、便于记录 hit_ids、便于最终答案阶段对齐 113 引用编号。若返回纯文本，后处理又要用正则扒拉，失去 FC 的结构化优势。",
        "对「你好」「谢谢」类闲聊，理想行为是直接 assistant 回复不触发工具。若误触发 search_kb，会平白增加数百毫秒检索延迟，还可能搜到无关热门文档导致奇怪答案。可以在网关用轻量分类器先拦截极度闲聊，再进入 FC 路由。",
        "与 121 越权过滤结合时，principal 必须从服务端 JWT 解析，在 dispatch_tool 里注入，而不是让模型在 arguments 里传 user_id。模型可能被诱导传他人 id。工具层是安全边界，不能信任模型自觉。",
        "日志里记录 tool_name、latency、args_hash、返回 chunk 数量，每周 review 误触发样本，回写 description 与 few-shot。FC 系统的质量靠持续迭代工具文案，不是靠一次性把 temperature 调到零。",
        "若最终答案需要 JSON 结构给下游系统，最后一跳可以 bind response_format，与 tool 阶段分离。不要在 tool 里要求模型输出最终用户可见长答案，工具只负责取数，答案生成仍由后续 assistant 完成，职责清晰。",
        "流式 UI 上对工具阶段显示「正在查询知识库」比沉默等待更友好。工具阶段结束后再开始 delta 流式。用户若长时间看不到反馈，会重复点击发送，造成重复检索与重复计费。",
        "面试常问：FC 与硬编码 RAG 如何选？答：合规单一知识域 FAQ 优先硬编码；混合意图、多数据源、需要动态路由时用 FC；无论哪种，ACL 在服务端强制执行，引用契约在应用层统一。",
        "工具调用的单元测试应 mock 执行层，不要真打向量库。断言模型返回 tool_calls 时 dispatch 收到正确参数；断言 max_rounds 截断；断言 ACL principal 传入 search_kb。集成测试再跑真库。",
        "对多语言团队，工具 description 可同时写中文触发条件与英文反例，减少模型误路由。最终用户答案语言仍由 system 控制，与工具文案语言可不同。",
        "FC 版本升级要关注供应商差异：OpenAI、Azure、本地 vLLM 对 tools 字段支持度不同。上线前在目标网关跑 golden tool_call 样例，避免生产才发现不支持 parallel_tool_calls。",
        "将 FC 与评测流水线结合：记录「本应触发 search_kb 却未触发」与「不应触发却触发」两类错误，分别算召回与精确率，周会复盘改 description 与 few-shot。",
    ],
    "langchain-core": [
        "LangChain 在企业里的价值常被高估也被低估。高估在「装了就能 RAG」；低估在「统一 Runnable 接口后换模型与观测更省事」。理性态度是：C 轨手写跑通后再引入 D 轨，用框架收拢重复胶水，而不是从零依赖黑盒 Chain 看不懂检索逻辑。",
        "安装依赖时坚持最小集合：langchain-core、langchain-openai、langchain-chroma 三件套能覆盖多数 PoC。langchain-community 体积大、传递依赖多，只在需要特定集成时再装。锁版本文件应进 CI，升级跑金标 invoke 对比输出差异。",
        "ChatPromptTemplate 应与 110 篇 RAG 模板版本同号管理。例如 rag_prompt_v3.yaml 进 git，变更走 PR review。不要把 prompt 散落在多个 Python f-string 里，否则合规审查无法回答「上线那天用的规矩是什么」。",
        "Runnable 的 batch 适合离线评测与夜间批处理，不要在高 QPS 在线路径滥用大 batch，否则内存与排队延迟上升。在线路径用 invoke 或 astream，批处理用 batch，职责分明。",
        "回调系统可以把 token 使用量打到 Prometheus，配合 27 篇计费模型做 per-tenant 成本看板。比手工在每次 openai 调用后 parse usage 更不易漏。",
        "与 FastAPI 集成时，路由层负责 HTTP、鉴权、SSE 事件包装；LangChain 链只负责产出文本或消息流。不要让 Chain 直接操作 WebSocket 或数据库 session，保持分层便于测试。",
        "Embeddings 类换供应商时，向量库必须重建索引。团队 wiki 应记录当前 production collection 对应的模型名与维度，避免新人用错 embedding 查询导致「检索全空」却以为是 LangChain bug。",
        "学习路径：先 125 核心 Runnable 与消息，再 126 LCEL 组合，再 127 Retriever 接 C4/C5。跳过 125 直接抄 LCEL 模板，出问题时很难 debug 中间类型流转。",
        "D 轨不是替代 C 轨面试题。面试官仍可能让你手写 retrieve 与 prompt 组装。LangChain 是工程加速器，不是知识替代品。",
        "给产品经理的解释：LangChain 像统一规格的积木，换模型换库像换积木供应商，房子结构（RAG 流程）不变。不是买了积木就不用懂建筑力学。",
        "内部培训建议做对照 lab：同一 Mini-RAG 用裸 SDK 与 LangChain 各实现一遍，对比行数、可测性、换模型成本。用数据决定团队标准，而不是跟风。",
        "注意 license 与供应链：partner 包传递依赖要进 SBOM。金融客户常问 LangChain 是否引入未知依赖，锁版本与最小安装是合规答复的一部分。",
        "从 125 到 127 三节构成 D 轨最小闭环：核心抽象、LCEL 组合、Retriever 接检索。学完应能向同事演示十行 LCEL RAG，并指出 ACL 写在哪一层。",
        "Runnable 的 config 可传 max_concurrency 控制 batch 并发，避免压垮向量库。在线单条 invoke 时不要误用高并发 batch 配置。",
        "SystemMessage 内容变更要走 PR 评审，与 110 篇 RAG 模板版本联动。不要私下改 system 导致线上引用格式突变。",
        "本地开发可用 Ollama partner 替代 OpenAI，但 embedding 与 chat 模型维度、能力不同，PoC 通过后再接企业网关。",
        "LangChain 文档更新快，以你锁定的版本官方文档为准，勿用搜索引擎跳转到最新版不兼容 API。",
        "单元测试优先 mock ChatModel 返回固定 AIMessage，测 prompt 组装与链逻辑，减少 API 费用与 flakiness。",
        "与 Pydantic v2 集成时注意 langchain-core 版本要求，升级 Python 或 Pydantic 时一起跑 CI。",
        "团队应维护「LangChain 不用清单」：例如超高 QPS 纯检索无需 LC；单文件脚本无需 LC。",
        "On-call 遇到 ImportError 先查 partner 包是否安装，遇到空检索先查 filter 与 collection 名，再怀疑框架。",
        "142 篇毕业标准：五分钟白板画出 core、partner、Runnable、三消息类型、与 126 127 衔接箭头。",
    ],
    "langchain-lcel": [
        "LCEL 的可读性来自管道直观，但复杂业务仍需要注释与命名中间 Runnable。给 Parallel 字典的每一支加注释说明输入输出类型，否则三个月后自己都看不懂 context 支路为何报错 KeyError。",
        "RunnableLambda 里写过多业务逻辑是反模式。超过十行建议抽成普通函数再包 Lambda，或写自定义 Runnable 类。否则单测困难，也无法复用 ACL 与日志逻辑。",
        "流式链调试可以用 astream_events 观察 on_chat_model_stream 事件，定位卡在检索还是生成。比 print 每个 chunk 更结构化。生产环境关闭详细事件，只保留延迟指标。",
        "with_retry 适合短暂网络抖动，不要用来掩盖持续 401 或错误模型名。重试三次仍失败应快速失败并告警，避免用户长时间看 spinner。",
        "LCEL 链的输入 schema 可以自动生成 OpenAPI 片段，用于内部工具平台。输入 dict 的 question 字段与可选 session_id 对齐 118 session API，减少前后端扯皮。",
        "与 107 预算结合时，format_docs 应接受 max_chars 参数，在 Parallel 后加 RunnableLambda 截断 evidence。不要假设 retriever 返回条数少就一定短，单条 chunk 可能上万字。",
        "拒答分支用 RunnableBranch 表达比 if else 嵌套更易读。空检索条件要写清：hits 为空或分数全低于阈值都算空，与 99 篇一致。",
        "团队 code review 对 LCEL 的检查项：变量名对齐、filter 是否存在、是否误并行依赖历史的步骤、stream 路径是否接 116 事件、citations 是否在链外组装。",
        "背诵：dict 进 Parallel，question 用 Passthrough，context 是 retriever 竖线 format，再 prompt llm parser。五步口诀对应 127 与 126 的核心 RAG 链。",
        "LCEL 链过长时可拆 named subchain：rewrite_chain、retrieve_chain、answer_chain，再用 Parallel 或顺序组合。可读性与单测性优于一条十米长的管道。",
        "异步部署用 ainvoke 与 astream，注意 FastAPI 路由 async def 内不要混阻塞 IO。检索若阻塞，用 asyncio.to_thread 包一层，避免拖垮事件循环。",
        "与 123 JSON 输出组合时，parser 选 JsonOutputParser 或 PydanticOutputParser，放在链末。检索与生成仍可流式，但最终 JSON 往往需非流收束，产品上要提示用户稍候。",
        "记录每次链变更的 golden 输出 diff，升级 langchain-core 小版本也可能改变 prompt 格式化细节。CI 里跑三条金标答案相似度，低于阈值阻断发布。",
        "RunnableParallel 字典键顺序不影响执行，但日志阅读顺序影响调试体验，建议 context 写前 question 写后。",
        "itemgetter 变体适合输入已是 dict 的 API，与 RunnablePassthrough 二选一，勿混用导致类型嵌套。",
        "链的 save 与 load 了解即可，生产更常用代码即配置，避免 JSON 链与代码分支双轨。",
        "astream_log 调试后记得关，verbose 流会打满磁盘。",
        "与 118 多轮结合：链输入可扩展为 dict 含 question 与 chat_history，retrieve 支路只用改写后 query。",
        "LCEL 链中不要直接操作全局 session，通过 config metadata 传 session_id 到回调写日志。",
        "143 篇毕业标准：现场写 Parallel RAG 链并 stream 三字，口头说明 citations 在链外原因。",
        "遇到 TokenExpiredError 在回调层统一重试刷新，不要每条链各自处理。",
        "培训时对比 invoke 与 stream 的 UX 差异，让前端理解为何需要 116 事件而不只是 print chunk。",
    ],
    "langchain-retriever": [
        "Retriever 是 C5 检索策略进入 LCEL 的插头，不是新策略本身。换 MMR、MultiQuery、混合检索，仍要回到 91、93、101、105 篇理解原理，否则只会调参数不知 bad case 根因。",
        "as_retriever 的 search_kwargs 要与入库 metadata 字段一致。doc_id、acl_group、version 等若拼写不一致，filter 会静默返回空，表现为「LangChain 坏了」其实是 schema 错了。",
        "自定义 Retriever 时，在 _get_relevant_documents 里打审计日志：user_id、filter、返回 doc_id 列表。121 篇越权审计依赖这些日志，不要只 log query 明文。",
        "EnsembleRetriever 权重要在验证集上调，不要拍脑袋零点六零点四。混合检索的两路必须应用相同 ACL filter，否则稀疏路泄漏机密是经典事故。",
        "ParentDocumentRetriever 适合长政策 PDF，小块找位置大块读上下文。与 65 篇 parent 策略一致。注意父文档可能很长，pull 父级后仍要过 107 预算截断。",
        "MultiQueryRetriever 提升 Recall 但增加成本。高 QPS 时对低置信 query 才触发，或夜间批处理用 batch 跑多 query，白天在线用单 query 保延迟。",
        "score_threshold 检索要把阈值与 embedding 模型一起版本化。换模型后旧阈值可能全空或全满。配置中心用 pair：embed_model_id + threshold。",
        "create_retriever_tool 暴露给 124 FC 时，工具 description 要写清与硬编码 RAG 相同的触发条件，否则一路硬编码一路 FC 行为不一致，用户困惑。",
        "作业：同一问题对比 k 三与 k 十的 prompt token 与答案质量；加 acl filter；用 callbacks 打印 doc_id；接 116 SSE 流式网关完成 D 轨小闭环。",
        "Retriever 文档要强调：invoke 入参是 query 字符串，不是 messages 数组。多轮场景先 118 改写再传入 retriever，不要把整段对话 JSON 塞进去。",
        "当检索结果为空时，LCEL 链应走拒答分支而不是让 LLM 硬答。空结果也消耗一次向量查询，要在日志里记录 empty_hit 便于调阈值或修索引。",
        "向量库升级或 reindex 期间，Retriever 可能返回变少。要有降级策略：提示「知识库更新中」而非胡编。运维 flag 控制只读模式。",
        "127 篇学完后，建议回到 C5 做一周检索策略实验：MMR、MultiQuery、混合、rerank 各改 Retriever 配置，用同一评测集比较，建立「策略—Retriever 参数」对照表，而不是只会 as_retriever(k=5)。",
        "VectorStore.add_documents 批次大小影响入库速度，与 67 embedding batching 篇一致，过大占内存过小费 API。",
        "检索日志建议采样：高 QPS 时全量 doc_id 日志爆存储，1% 采样足够发现 filter 系统性错误。",
        "Chroma where 语法随版本变化，升级 chromadb 要跑 filter 单测，勿生产直接升。",
        "FAISS 自建 VectorStore partner 时，id_map 与 ACL 仍要自己维护，Retriever 不 magically 解决。",
        "144 篇毕业标准：演示 filter 后 finance 用户搜不到 finance 以外机密，并打印 audit 日志。",
        "与 96 BGE rerank 配合：Retriever k 可略大，rerank 在链外或 RunnableLambda 后收窄。",
        "SelfQueryRetriever 了解即可，metadata 字段描述要全，否则 LLM 生成 filter 胡写。",
        "Retriever 返回 Document 的 page_content 不要含超大 base64 图片，多模态另走 56 篇管线。",
        "每周检索质量会议看 Recall@k 与空结果率，空结果率高先修索引与 filter，勿先怪 LangChain。",
        "Retriever 是连接 C 轨检索智慧与 D 轨编排语法的桥梁，144 篇读完应能独立回答「k、filter、MMR 各解决什么问题」而不查阅文档。",
        "将本篇与 76 Chroma、91 稠密检索、121 越权过滤 串联复习，形成「入库—检索—过滤—编排—流式」完整心智地图，是 D 轨主线篇的合格终点。",
    ],
}
