# -*- coding: utf-8 -*-
"""Final top-up paragraphs — substantive, per-slug banks."""

TOPUP = {
    "langchain-vectorstore": [
        "企业落地 LangChain VectorStore 时，要把「嵌入模型版本」「collection 名称」「persist 路径」三件事写进配置中心，禁止散落在笔记本脚本里。",
        "与原生 Chroma 对照实验建议每月做一次：同一 query 打印 Top-5 chunk_id，若与 LangChain 路径不一致，优先查 ids 与 filter 而不是先调 prompt。",
        "FAISS 路径适合离线评测与只读副本；在线 ACL 复杂时仍推荐 Chroma 或带 metadata filter 的向量库，避免检索后过滤漏网。",
        "VectorStore 层不要调用 cross-encoder；宽召回在 store，精排在 Retriever 链或独立 Runnable，延迟可控。",
        "ingest 任务结束写 manifest：embed_model、collection、chunk_count、created_at，与参数版本表联动，方便 bad case 回放。",
    ],
    "langchain-document-loader": [
        "DirectoryLoader 扫大型 NAS 时必须配合增量 manifest，记录 mtime 与 content_hash，未变文件不进入 Splitter，节省 embed 成本。",
        "PyMuPDFLoader 读扫描件 PDF 常得空文本，OCR 是前置工序，Loader 只消费已 OCR 的可搜索 PDF 或纯文本。",
        "metadata 在 Loader 层落盘：doc_id、source、page、acl_group、mime、content_hash 缺一不可，缺字段拒绝下游。",
        "混合扩展名目录用 loader_map：按 MIME 或后缀选 Loader，未知类型进死信队列，避免二进制当 UTF-8 读。",
        "WebLoader 抓外网要注意合规；内部 Confluence 优先 API 导出 Markdown，结构稳定且易审计。",
        "Loader 输出 JSONL 中间态供数据组抽检，与金标 chunk_id 对齐，缩短解析类 bad case 定位时间。",
        "多租户场景 root 路径按 tenant 隔离，禁止用户输入拼接 glob，防路径遍历与跨租户读取。",
        "与 Parser 协议衔接：自研 Parser 用 ParserLoader 薄包装，复杂版式不进 Loader 子类，保持可单测。",
    ],
    "langchain-text-splitter": [
        "切块参数不要拍脑袋：用二十条金标网格搜索 size 与 overlap，记录 Recall@5 与平均 chunk 数，最优写入参数版本表。",
        "中文制度文档分隔符建议含句号、问号、叹号与段落换行，避免从「第一条」中间切断。",
        "Markdown 先 Header 粗切再 Recursive 细切，保留 h1/h2 metadata，利于按章节过滤检索。",
        "TokenTextSplitter 对接 OpenAI embed 时，max_tokens 应低于模型上限，防 API 截断。",
        "每个 chunk 必须有唯一 chunk_id，通常 doc_id 加序号，供增量 upsert 与评测对齐。",
        "overlap 增大时 Top-K 易重复相邻 chunk，检索侧配合 MMR 或按 section 去重。",
        "改 splitter 参数必须重建向量索引，不能只改在线 k，否则金标与线上行为不一致。",
        "与 C 模块 57-65 手写切块对照 diff，确认边界差异在可接受范围再切换 LC Splitter。",
    ],
    "llamaindex-index-types": [
        "LlamaIndex VectorStoreIndex 构建时同步 embed，大库应分批 insert，内存与批处理策略同 LangChain ingest。",
        "Node 可带关系边，适合图索引实验；生产向量问答多数只需 Document 等价物与 metadata。",
        "SummaryIndex 仅适合短文 demo，企业长手册仍会撞上下文窗口，不能替代检索。",
        "TreeIndex 层次检索复杂度高，更稳做法是 Markdown 标题切块加向量检索。",
        "KeywordTableIndex 类似稀疏检索，LangChain 侧常用 BM25Retriever，了解 LI 名词即可。",
        "ComposableGraph 多库合并不宜默认上线，评估延迟与运维后再考虑。",
        "storage_context 绑定 vector_store，读 LI 代码时对应 Chroma 或 Qdrant 持久化概念。",
        "主线用 LangChain 时，LI 索引篇两小时阅读加 demo 即可，避免双栈并行。",
    ],
    "llamaindex-query-engine": [
        "Query Engine 一站式封装检索与合成，内部仍可拆成 retriever 与 response_synthesizer 理解。",
        "response.source_nodes 提供引用素材，映射 grounding 与行内 citations，LC 侧从 retriever 结果手写。",
        "response_mode 选 compact 或 tree_summarize 成本高，企业常用固定 prompt 模板加 LCEL。",
        "sub_question 模式类似查询分解，多次检索加 LLM，延迟与费用显著上升。",
        "streaming 对接 SSE 与打字机 UI，协议层统一，框架只提供 token 迭代器。",
        "生产团队已标准化 LCEL 与 LangSmith 时，不必另起 Query Engine 黑盒路径。",
        "了解档也要画检索加合成两框图，面试能说清与 LCEL 的模块对应关系。",
        "Postprocessor 链类似阈值过滤与去重，LC 在 Retriever 后显式实现更清晰。",
    ],
    "llamaindex-agent": [
        "ReActAgent 与 Function Calling 同属思考、选工具、观察循环，治理策略一致。",
        "QueryEngineTool 的 description 要写清适用与禁止场景，工具内 Retriever 必须带 ACL。",
        "max_iterations 与总 timeout 必设，防账单爆炸与无限循环。",
        "Agent 路径难审计，金融监管场景对外服务用固定 RAG 加拒答。",
        "工具参数用 schema 校验，防模型编造 doc_id 或过大 k。",
        "trace 记录每轮 tool_name、latency、chunk_ids，便于成本与合规复盘。",
        "与固定多跳管道比，Agent 灵活但可控性低，默认内部探索用。",
        "动手实验不超过两小时，然后回到 LangChain Retriever 固定链深化。",
    ],
    "haystack-pipeline": [
        "Haystack 2 用 Component 显式端口，Pipeline.connect 编译期检查，可借鉴设计自研 DAG。",
        "组件单测 run 输入输出，比端到端 LLM 测试稳定，值得在自研管道推广。",
        "pipeline YAML 序列化动机与配置驱动管道相同，运维可改 top_k 不发版。",
        "DocumentJoiner 体现 RRF 融合思想，LC 用 EnsembleRetriever 或自研 fusion。",
        "Haystack 常画 ES 加向量双写，学拓扑不必迁栈。",
        "团队主栈 LangChain 时，Haystack 作设计参考，禁止同一请求双框架。",
        "手绘 ingest 与 query 两图对照 LCEL，是本篇核心交付物。",
        "了解档四小时阅读加手绘即可勾选路线图，不引生产依赖。",
    ],
    "pipeline-vs-framework": [
        "架构取舍用分层表表达：Parser、Splitter、Embedder、Store、Retriever、Generator、编排各选自研或框架。",
        "PoC 阶段 LangChain 加 Chroma 验证业务，Parser 尽快协议化防锁定。",
        "ACL 与审计日志建议自研，不把安全边界交给 system prompt。",
        "金标与 RAGAS 守门，任何替换跑回归与 A/B，用数据结束争论。",
        "技术债信号：升级断链、双框架并行、无金标上线，应冻结功能还债。",
        "ARCHITECTURE 一页写清回滚与 RACI，与参数版本表同库维护。",
        "供应商交付要可导出 chunk、向量、金标，合同写迁移权。",
        "面试强调单栈纪律、可插拔协议、评测门禁，而非框架站队。",
    ],
    "pluggable-parser-splitter-embedder": [
        "Parser 协议 parse 路径得 RawDocument，Splitter 得 Chunk 列表，Embedder 得向量，三者窄接口可单测。",
        "REGISTRY 加 build_pipeline 从 YAML 组装，配置键不存在应 CI 失败。",
        "契约测试对 fixtures 断言 doc_id、chunk_id 唯一、embed 维度一致。",
        "manifest 记录 parser、splitter、embedder 版本与 chunk_count，查询日志带 manifest_id。",
        "LangChain Loader、TextSplitter、Embeddings 只做薄适配，逻辑留在协议实现。",
        "换 embed 模型必须新建 collection 全量重建，旧库只读归档。",
        "Parser 单文件失败跳过并进死信，不拖垮整批 NAS 扫描。",
        "与 137 Store Retriever Generator 对称，138 配置拧紧全链，完成数据入口地基。",
    ],
}
