# -*- coding: utf-8 -*-
"""Expand7: last top-up."""

E7 = {
    "173.code-highlight-rag-tutorial.md": """本篇是 F2 了解篇，但直接影响技术类知识库 Demo 专业度。请将 CodeBlock 纳入设计系统组件库，版本随 `highlight.js` 安全更新而升级。与运营约定：发布到知识库的 Runbook 原文尽量使用标准围栏语法，减少前端启发式猜测。每周 sample 十条含代码答案，检查复制成功率与色彩对比度。完成学习后前往 [174 流式打字机](174.streaming-typewriter-ui-tutorial.md)，把静态高亮与动态流式结合。团队可在季度复盘时对比「接入高亮前后」运维工单的「复制错误」类 ticket 是否下降。若你维护多套主题，记得在 Storybook 做视觉回归。对实习生培训时，先让 TA 手工复制无高亮代码失败一次，再展示本篇组件，印象更深。最后，在路线图上勾选第 190 条，并通知 PM 技术 Demo 已可对外展示 Runbook 问答。若时间充裕，可对比 shiki 主题与 hljs 在同一代码样本上的渲染差异，写入团队 ADR（架构决策记录）备查。复制 handler 可将弯引号规范为直引号，减少终端粘贴失败；该行为可通过设置开关默认关闭，以免改变用户预期。""",
    "174.streaming-typewriter-ui-tutorial.md": """流式打字机是用户感知 AI「在场」的关键。除本篇外，请熟读 [116 SSE RAG](116.sse-rag-streaming-tutorial.md) 后端事件表，前后端各有一名 owner 签字协议版本。预发环境用真实模型测 TTFT 分布，写入 SLO 看板。切忌在检索阶段播放假打字动画——诚实等待比虚假进度更能建立信任。完成后接 [175 中断](175.abort-controller-stream-tutorial.md) 与 [176 引用卡片](176.citation-card-ui-tutorial.md)，形成完整问答体验。建议录制对比视频：左非流式整段跳出，右流式打字机，给非技术干系人观看。将 rAF 合并逻辑封装为可单测纯函数，避免 Hook 过于臃肿。对超长答案启用「回到底部」浮动按钮。路线图第 191 条与第 22 条流式 UI 一并勾选。""",
    "175.abort-controller-stream-tutorial.md": """中断是成本与体验的双赢：用户不再被长答案绑架，企业不再为无人阅读的 token 买单。务必让后端、前端、财务三方理解「停止后检索成本可能已发生」。文档化 abort 与 error 的 UI 差异，避免客服误判。若未来上 [117 WebSocket](117.websocket-rag-streaming-tutorial.md)，保持 stop() API 稳定。下一步用 [176 引用卡片](176.citation-card-ui-tutorial.md) 让停止后的 partial 答案仍可展示已到达的引用信息（若有）。在 on-call 手册写明：用户报「停不下来」先查 Network 是否 canceled，再查后端 disconnect 日志。将 abort 率纳入周报，异常飙升时联动模型延迟与答案长度分析。路线图第 192 条勾选后，即满足阶段 0/4 对「中断」的验收表述。""",
    "176.citation-card-ui-tutorial.md": """引用卡片是 Grounding 的「第二屏」。设计评审时让法务与业务方现场点卡片：能否在十秒内找到依据文档与页码？若不能，优先改 excerpt 与 title，而非加花哨动画。与 [113 行内](113.inline-citation-tutorial.md) 编号严格一致是红线。移动端务必测试 Bottom Sheet 内滚动与外层聊天列表不冲突。完成后进入 [177 侧栏预览](177.source-preview-sidebar-tutorial.md)，让卡片点击有明确归宿。建议为卡片点击埋点，月度查看 Top 被点文档，反哺运营补库。空 citations 时整个列表区域不渲染，避免「参考来源 (0)」笑话。路线图第 193 主线项要求与 115 导航字段对齐，上线前用 JSON Schema 校验 citations 响应。""",
    "177.source-preview-sidebar-tutorial.md": """侧栏预览是 B2B 采购演示的高光时刻：左问右证，胜过千言万语。signed URL 过期策略要与法务文档保留期一致。audit log 保留多久提前写进隐私政策。与 [178 PDF 高亮](178.pdf-highlight-locate-tutorial.md) 联调时，用同一 chunk 端到端走通。若无 PDF 仅 Markdown，侧栏仍应可用，勿等 178 才上线 194 项能力。预发用 nginx 同源部署预览 API，避免 CORS 演示翻车。键盘用户务必走一遍：点引用→焦点入侧栏→Esc 关闭。将双栏截图放入售前 PPT 第二页。路线图第 194 条勾选代表 F2 溯源 UI 主体完成。""",
    "178.pdf-highlight-locate-tutorial.md": """本篇收官路线图 190～195，并指向 [ENTERPRISE_RAG_ROADMAP 阶段 4](ENTERPRISE_RAG_ROADMAP.md#阶段-4全栈产品) 全栈验收。PDF 高亮是加分项，但能让法务与审计一眼信服。bbox 与 OCR 是进阶，PoC 用跳页加文本搜索即可上线。请立即打开 projects/04-fullstack-assistant，按 §11 验收表录制五分钟 Demo。下一阶段学习 196 上传界面与阶段 5 生产化。感谢坚持到 F2 系列最后一篇。把本篇与 171～177 的组件清单贴在项目 README，方便新人一天内跑通溯源链路。面试时用阶段 4 验收表当 checklist 逐项讲解。全栈 RAG 不仅是后端向量库，更是用户愿意信任的界面——你已完成这一环。""",
}
