# -*- coding: utf-8 -*-
"""Large Chinese expansion blocks for batch 164-172 (>=5000 hanzi target)."""

def _blocks(*sections: str) -> list[str]:
    return list(sections)


EXTRA_EXPANSION: dict[str, list[str]] = {
    "jwt-auth-rag": _blocks(
        "### 14.30 RS256 密钥对与 JWKS\n\n多服务架构下 **签发服务** 持私钥，**RAG API** 只拉 **JWKS** 公钥验签。`/.well-known/jwks.json` 缓存 **15 分钟**；kid 轮换时 **旧公钥保留** 至所有 access 过期。PoC 可 HS256 单密钥，**预发必须** 演练轮换 runbook。",
        "### 14.31 OAuth2 Password Flow（PoC）\n\n企业最终走 **OIDC 授权码 + PKCE**；PoC 可用 **Resource Owner Password** 换 token **仅限内网**。生产 **禁用** password flow 防 **钓鱼**。FastAPI `OAuth2PasswordBearer` 与 `OAuth2PasswordRequestForm` 对齐 [170 OpenAPI](170.openapi-swagger-docs-tutorial.md) 文档。",
        "### 14.32 与 [165 RBAC](165.rbac-rag-tutorial.md) claims 映射\n\nJWT `roles: [\"employee\"]` **不等于** `groups: [\"finance_only\"]`。IAM 同步脚本 ** nightly ** 更新 groups；roles 管 **ingest/admin** API。映射表 **单源** 存 Postgres `principal_mapping`，签发 token 时 **join 查询**。",
        "### 14.33 双因素与 step-up\n\n访问 **break_glass 财务检索** 可要求 **step-up MFA**：短效 **elevated token** 含 `amr: [\"mfa\"]` claim，**5 分钟** 过期。RAG **不实现 MFA UI**——委托 IdP；API **只验** elevated claim。",
        "### 14.34 Service Account JWT\n\nCelery worker、定时 rebuild 用 **client_credentials** 换 **服务 JWT**，scope=`rag:ingest:system`。**禁止** 与用户 refresh 共用密钥。**aud** 设为 `rag-internal` 防 **token 拿到外网**。",
        "### 14.35 Cookie vs Authorization 头\n\n同源 Next.js [171](171.chat-message-list-ui-tutorial.md) BFF 可读 **HttpOnly Cookie** 转发 Bearer 给 Python API；跨域 SPA **必须** Authorization 头 + **CORS 白名单**。两种模式 **JWT payload 相同**。",
        "### 14.36 与 [116 SSE](116.sse-rag-streaming-tutorial.md) 鉴权\n\nEventSource **不能** 自定义头（旧浏览器）——用 **query token 短期** 或 **Cookie 同域**。token **仅 SSE 用**、**60s TTL**、**scope=sse:chat**；流结束 **作废**。",
        "### 14.37 渗透测试清单\n\n1. alg=none；2. 弱密钥爆破；3. 改 tenant_id payload；4. 重放过期 token；5. refresh 重用；6. 无 Authorization 访问 /chat；7. body 注入 user_id **应忽略**。",
        "### 14.38 日志与合规\n\n**禁止** 日志打印 JWT 全文或 **Authorization 头**；记 **sub、tenant、jti、endpoint、latency**。GDPR **删除用户** 时 **黑名单 jti** + **删 refresh**；历史日志 **保留 hash(sub)**。",
        "### 14.39 与 [53 ACL](53.metadata-acl-tutorial.md) 字段一致性\n\n签发 token 前 **查用户 groups** 必须与 chunk `acl_group` **枚举一致**。新增 `legal_only` 组 **先** 迁移 metadata **再** 发 token。",
        "### 14.40 多区域部署\n\nJWT **iss** 含区域；**aud** 含 `rag-api-eu`。**禁止** 欧洲用户 token 在 **美国区 API** 验签通过（**iss/aud 不匹配**）。",
        "### 14.41 故障：时钟不同步\n\nNTP 漂移致 **iat 在未来**——验签 **leeway** + 监控 **401 激增**。K8s 节点 **强制 chrony**。",
        "### 14.42 与 [166 tenant](166.tenant-isolation-backend-tutorial.md) 联调\n\n**无 tenant_id claim** 的 token **一律 401**——**不设默认 tenant**。集成测试 **必含** 缺 claim 负例。",
        "### 14.43 密钥泄露应急\n\n1. 轮换 SECRET/私钥；2. 缩短全局 access TTL 至 5min；3. refresh 全失效；4. 审计 **异常访问**；5. postmortem。",
        "### 14.44 初学者练习\n\n用 python-jose **手写** encode/decode；改 payload 一字节 **验签失败**；用 pytest ** parametrized** 跑 **6 负例**。",
        "### 14.45 与 API Gateway 分工\n\n网关：验 JWT、限流 [169]、WAF；RAG 服务：**二次验 aud**、**RBAC**、**ACL filter**。**纵深** 不重复造轮子但 **不假设网关万能**。",
        "### 14.46 Token 大小\n\ngroups 过多致 **Header 过大**——**压缩为 permissions bitmap** 或 **服务端 session 存 groups**、JWT 只带 **session_id**（架构升级路径）。",
        "### 14.47 与 [121 越权](121.unauthorized-doc-filter-tutorial.md) E2E\n\nE2E：**合法 JWT + guest groups** 问 finance → **ACL_DENIED**；**fin groups** → **有答案**。身份链 **正确** 才测 ACL。",
        "### 14.48 移动端 Deep Link\n\nApp 从邮件 link 带 **一次性 code** 换 token——**禁止** URL 里 **长期 JWT**（Referer 泄露）。",
        "### 14.49 与 [170 OpenAPI](170.openapi-swagger-docs-tutorial.md)\n\n`/auth/login` **response** 文档 **access_token** 字段；**securitySchemes Bearer** 全局。前端 codegen **Authorization Interceptor**。",
        "### 14.50 团队 RACI\n\n**安全** 定算法与轮换；**后端** 实现 Depends；**前端** 存 token 策略；**QA** 渗透用例；**SRE** NTP 与密钥 KMS。",
        "### 14.51 面试：JWT 在 RAG 哪一步？\n\n**HTTP 层最先**——无合法 Principal **不进入** retriever。检索 filter 用 **groups/tenant**，不是 **decode 后信任 body**。",
        "### 14.52 与 Session 混合\n\n**Hybrid**：JWT access + **服务端 session 存 refresh 元数据**（device_id、IP）。**吊销 refresh** 查 session 表。",
        "### 14.53 完结检查\n\n**181 JWT** 交付：**§9 跑通** + **6 负例** + **与 165/166 联读** + **OpenAPI Bearer** 文档化。",
        "### 14.54 延伸阅读\n\n[164→165→166→121→53] 身份与隔离链；[167→168→169] 模型与限流链；[171→172] 前端安全链。",
        "### 14.55 给产品经理\n\n「用户登录后拿到 **工牌 JWT**，每次问知识库 **刷卡**；工牌里 **部门标签** 决定 **能搜哪些文件**——不是前端说自己是财务就算数。」",
        "### 14.56 常见错误码\n\n| code | HTTP | 含义 |\n|------|------|------|\n| AUTH_MISSING | 401 | 无 Bearer |\n| AUTH_INVALID | 401 | 验签失败 |\n| AUTH_EXPIRED | 401 | exp 过期 |\n| TENANT_MISSING | 401 | 无 tenant claim |",
        "### 14.57 与 [156 FastAPI 结构](156.fastapi-project-structure-tutorial.md)\n\n`auth/` 包：`deps.py`、`jwt_utils.py`、`routes.py`；**router 不含** 检索逻辑。",
        "### 14.58 生产 checklist\n\n- [ ] HS256/RS256 选型文档\n- [ ] 密钥 KMS\n- [ ] access ≤30min\n- [ ] refresh 轮换\n- [ ] tenant claim 必填\n- [ ] 渗透 7 项\n- [ ] 日志无 token",
        "### 14.59 与 [163 重试](163.retry-dead-letter-tutorial.md)\n\n**401 不重试**；客户端 **refresh 一次** 再重放原请求；**仍 401** 跳登录。",
        "### 14.60 篇末\n\n**JWT 认证 RAG API 完全指南 · 路线图 181 · 地基篇** — 身份可信，ACL 才有意义。",
    ),
    "rbac-rag": _blocks(
        "### 14.30 权限字符串命名规范\n\n`rag:chat`、`rag:ingest`、`rag:doc:delete`、`rag:admin:metrics`。**动词在后**；**通配** `rag:*` **仅 break_glass**。与 OAuth scope **1:1 映射** 便于 **第三方集成**。",
        "### 14.31 Casbin 模型（了解）\n\n`[request_definition]` `r = sub, obj, act`；`[policy]` `p = sub, obj, act`；**adapter 存 Postgres**。规则 **>50 条** 再引入；PoC **Depends 够用**。",
        "### 14.32 与 [164 JWT](164.jwt-auth-rag-tutorial.md)\n\nToken **roles** 是 **RBAC 输入**；**groups** 是 **ACL 输入**——PR review **禁止** 混字段。",
        "### 14.33 动态权限\n\n「文档所有者能删自己的 doc」——**ABAC** 叠加：`require_permission(\"rag:doc:delete\")` **且** `doc.owner_id == user.sub`。",
        "### 14.34 与 [157 上传](157.file-upload-multipart-tutorial.md)\n\n`multipart ingest` **必须** `rag:ingest`；**病毒扫描** 另服务账号 **不等同** 用户 ingest。",
        "### 14.35 管理后台\n\n`GET /admin/*` **仅** `tenant_admin` 或 `platform_admin`；**platform** 跨 tenant **必审计**。",
        "### 14.36 权限矩阵 CI\n\npytest **参数化** 角色×端点；**MR 改路由** 必须 **更新矩阵测试**。",
        "### 14.37 与 [121 ACL](121.unauthorized-doc-filter-tutorial.md)\n\n**有 rag:chat** 但 **无 finance group** → **chat 200** + **ACL 403/空 hits**——产品 **两种错误码** 分清。",
        "### 14.38 外包角色\n\n`contractor` 角色：**仅** `rag:chat` + groups=`contractor_docs`——**禁止** 继承 `employee` 全部 groups。",
        "### 14.39 权限缓存\n\nRedis `user:{{sub}}:perms` TTL **300s**；IAM webhook **失效缓存**。ingest/delete **实时查**。",
        "### 14.40 OpenAPI scopes\n\n[170](170.openapi-swagger-docs-tutorial.md) 每 path **security: [{{BearerAuth: [rag:chat]}}]**。",
        "### 14.41 审计\n\n**403 RBAC** 记 `sub, path, required_perm`——**区分** ACL_DENIED。",
        "### 14.42 面试\n\n「谁能 ingest？」→ **rag:ingest 角色** + **tenant 隔离** + **ingest 审计**；**不是** 能登录就能 ingest。",
        "### 14.43 与 [166 tenant](166.tenant-isolation-backend-tutorial.md)\n\n`tenant_admin` **不能** 赋 `platform_admin`——**垂直越权** 测试。",
        "### 14.44 前端 disable 按钮\n\nUI **隐藏 ingest** 给 user 角色 **体验**；**安全靠后端 403**。",
        "### 14.45 完结\n\n**182 RBAC** — API **能力门**；与 ACL **双壁**。",
        "### 14.46 案例：实习生\n\n实习生 roles=`user`，groups=`all_staff`；**不能** ingest；**不能** 看 finance——**两维独立测试**。",
        "### 14.47 案例：KB 编辑\n\n`editor` 可 ingest **不能** delete **他人** doc——**ABAC owner 检查**。",
        "### 14.48 权限膨胀治理\n\n季度 review **未使用 permission**；**合并** 冗余角色。",
        "### 14.49 与 SSO 组同步\n\nAD group `CN=Finance` → `finance_only` **映射表** versioned。",
        "### 14.50 篇末\n\n**RBAC 角色权限 RAG 完全指南 · 路线图 182** — 完。",
        "### 14.51 练习\n\n扩展 §9 **矩阵测试** 加 `editor`、`admin` 两行。",
        "### 14.52 错误响应\n\n```json\n{{\"code\":\"RBAC_DENIED\",\"required\":\"rag:ingest\"}}\n```",
        "### 14.53 与 Celery\n\nWorker 用 **service role** `rag:ingest:system` **不是** 用户 editor 角色。",
        "### 14.54 给 CTO\n\n「我们 **接口级 RBAC** + **chunk 级 ACL**；**双重** 才能上线企业库。」",
        "### 14.55 checklist\n\n- [ ] PERMISSIONS 表\n- [ ] require_permission 全覆盖写路由\n- [ ] 矩阵 CI\n- [ ] 403 埋点",
        "### 14.56 延伸\n\n[165→166→121] 安全链；[157→159] ingest 链。",
        "### 14.57 反模式\n\n`if user.is_admin` 散落 **20 处**——**集中** RBAC 模块。",
        "### 14.58 多租户 RBAC\n\n同 role 名 **tenant 内有效**；`tenant_admin` **不能** 改 **别 tenant 用户**。",
        "### 14.59 合规\n\nSOX 环境 **ingest/delete** **双人复核** workflow **叠加** RBAC。",
        "### 14.60 收束\n\n**API 动作授权** — RBAC 篇 **唯一职责**。",
    ),
    "tenant-isolation-backend": _blocks(
        "### 14.30 与 [89 namespace](89.multi-tenant-namespace-tutorial.md) 深度对照\n\n89 §4 四种模式 **本篇落地** 到 FastAPI middleware、SQL WHERE、S3 prefix、Chroma collection 名 **`kb_{{tenant_id}}`**。",
        "### 14.31 与 [53 ACL](53.metadata-acl-tutorial.md)\n\ntenant 内 **仍要** acl_group——**HR 与全员手册** 同 tenant **不同 group**。",
        "### 14.32 与 [121 越权](121.unauthorized-doc-filter-tutorial.md)\n\nfilter = `tenant_id AND acl_group IN (...)` **缺一不可**；121 **无 hits** 时 **ACL_DENIED**。",
        "### 14.33 ContextVar 传递\n\n异步 FastAPI **request.state** + **ContextVar** 双写；Celery **task 参数 signed tenant**。",
        "### 14.34 SQL 注入与 tenant\n\n**参数化** `WHERE tenant_id = %s`——**禁止** f-string 拼 tenant。",
        "### 14.35 对象存储\n\n`tenants/{{tenant_id}}/raw/` **IAM 策略** 前缀隔离；**presigned URL** **含 tenant 校验**。",
        "### 14.36 向量库\n\nChroma `get_collection(f\"{{tenant_id}}_main\")`；**禁止** default collection **混 tenant**。",
        "### 14.37 日志与 metrics\n\nPrometheus label **tenant_id 高基数** 问题——**采样** 或 **aggregate**；**审计日志** **必含** tenant。",
        "### 14.38 跨 tenant 报表\n\n**platform_admin** **只读 aggregate** **无 chunk 正文**——**差分隐私** 或 **统计层**。",
        "### 14.39 租户开通\n\nOnboarding：**建 collection** + **S3 prefix** + **DB schema 行** + **默认 quota** [169]——**脚本 idempotent**。",
        "### 14.40 租户注销\n\n**硬删** 向量+对象+DB；**备份** [90] **按 tenant 删**；**legal hold** 例外。",
        "### 14.41 测试数据\n\n**合成 tenant_a/tenant_b**；**禁止** 生产数据 **copy 到 dev** 无 **脱敏**。",
        "### 14.42 渗透\n\nJWT **改 tenant** → **403**；API **body.tenant_id** **忽略** 测试。",
        "### 14.43 与 [161 状态机](161.index-task-state-machine-tutorial.md)\n\n任务表 **tenant_id 列** **索引**；查询 **必须** 带 tenant。",
        "### 14.44 与 [159 Celery](159.celery-async-queue-tutorial.md)\n\n队列 message **HMAC(tenant_id, payload)**；worker **验签**。",
        "### 14.45 多 region\n\ntenant **数据驻留** `region=eu`；路由 **EU API** + **EU 向量库**。",
        "### 14.46 面试\n\n「如何防串库？」→ **JWT tenant + 全链路 filter + namespace + 测试 + 审计**。",
        "### 14.47 案例\n\nSaaS 1000 tenant：**metadata filter 不够** → **分 collection** + **连接池**。",
        "### 14.48 案例\n\n并购 **tenant 合并**——**reindex 到新 tenant** **不是** 改 metadata **了事**。",
        "### 14.49 与 [88 filter](88.metadata-filter-retrieval-tutorial.md)\n\nFilterExpr **编译** 到各引擎 **tenant Clause 必选**。",
        "### 14.50 篇末\n\n**183 租户隔离** — **tenant_id 铁律**。",
        "### 14.51 checklist\n\n- [ ] JWT tenant\n- [ ] middleware\n- [ ] SQL WHERE\n- [ ] vector namespace\n- [ ] cross-tenant 负例",
        "### 14.52 给法务\n\n「技术隔离 **tenant 边界**；**合同** 定 SLA 与 **删除权**。」",
        "### 14.53 延伸\n\n[89→166→121→53] 四篇 **租户安全闭环**。",
        "### 14.54 ORM\n\nSQLAlchemy **global filter** `with_loader_criteria` 自动 **inject tenant**。",
        "### 14.55 缓存\n\nRedis key **`{{tenant}}:{{key}}`** 前缀——**防** cache 串库。",
        "### 14.56 搜索聚合\n\n**不能** 跨 tenant **RRF 融合**——**产品** **单 tenant 会话**。",
        "### 14.57 开发踩坑\n\n本地 **忘记切 tenant** 测 **假通过**——**.env DEFAULT_TENANT** **仅 dev**。",
        "### 14.58 监控\n\n`cross_tenant_denied_count` **应为 0**；**激增** = **攻击或 bug**。",
        "### 14.59 练习\n\n§9 **加第三 tenant** 测 **互不可见**。",
        "### 14.60 收束\n\n**多租户后端隔离** — 企业 SaaS RAG **P0 能力**。",
    ),
    "openai-api-wrapper": _blocks(
        "### 14.30 与 [35 篇](35.openai-compatible-api-tutorial.md) 对照表\n\n35 教 **三要素** 与 **最小脚本**；167 教 **服务内 Facade**、**Depends 注入**、**tenant 日志**、**与 168 路由衔接**。",
        "### 14.31 接口隔离\n\n`LLMClient` **不含** 检索逻辑；`RAGService` **组合** retriever + llm——[156 结构](156.fastapi-project-structure-tutorial.md)。",
        "### 14.32 同步包装异步\n\n遗留 sync 代码 **`asyncio.run`** **禁** 在 FastAPI 内；**全 async** 或 **`run_in_executor`**。",
        "### 14.33 用量与 [27 Token](27.token-counting-billing-tutorial.md)\n\n封装层 **统一 record usage** 按 tenant 聚合 **FinOps**。",
        "### 14.34 多 provider\n\n`OpenAILLMClient`、`AzureOpenAIClient` **同 Protocol**；**factory** 按 env 选择。",
        "### 14.35 Mock 测试\n\n`FakeLLMClient.chat` 返回固定串；**embed** 返回 **确定性向量** 测检索集成。",
        "### 14.36 结构化输出\n\n[123 JSON](123.structured-output-json-tutorial.md) **`response_format`** 在封装层 **可选参数** `json_mode=True`。",
        "### 14.37 与 [116 SSE](116.sse-rag-streaming-tutorial.md)\n\n`async def chat_stream` **yield str**；路由 **StreamingResponse**。",
        "### 14.38 连接池\n\nhttpx **Limits** max_connections；**防** 并发 chat **打满** 出站连接。",
        "### 14.39 密钥轮换\n\n**双 Key** 环境变量；**失败** 切 **备用 Key** **不等同** 模型路由。",
        "### 14.40 国内网关\n\n`OPENAI_BASE_URL` 指向 **兼容网关**；**model 名** 用 **网关文档** 字符串。",
        "### 14.41 错误类型映射\n\n`RateLimitError` → 429；`AuthenticationError` → 502 **配置**；**不** 裸抛给用户。",
        "### 14.42 与 [168 路由](168.multi-model-routing-tutorial.md)\n\n`RoutingLLMClient` **装饰** `OpenAILLMClient`——**业务仍调** `LLMClient`。",
        "### 14.43 与 [169 限流](169.rate-limiting-api-tutorial.md)\n\n**出站 TPM** 与 **入站 QPS** **两层**；封装层 **可选 semaphore** 限并发 embed。",
        "### 14.44 观测\n\nOpenTelemetry **span** `llm.chat` 属性 model、tokens、tenant。",
        "### 14.45 面试\n\n「为何封装？」→ **换网关、重试、日志、mock、路由** **一处改**。",
        "### 14.46 反模式\n\n业务里 **15 处** `OpenAI()` **singleton 无 timeout**。",
        "### 14.47 案例\n\n从 OpenAI 迁 **DeepSeek**：**只改 env** + **routing.yaml**——**零业务 diff**。",
        "### 14.48 embed 批处理\n\n[67 批处理](67.embedding-batching-tutorial.md) 在 `embed()` 内 **自动 batch 128**。",
        "### 14.49 篇末\n\n**184 OpenAI 封装** — RAG **模型调用总线**。",
        "### 14.50 checklist\n\n- [ ] Protocol 定义\n- [ ] chat/embed 分 model\n- [ ] timeout+retry\n- [ ] usage 日志\n- [ ] Fake 测试",
        "### 14.51 延伸\n\n[35→167→168→169] **调用链**。",
        "### 14.52 与 [69 重试](69.embedding-retry-rate-limit-tutorial.md)\n\n**共享** 退避策略 config。",
        "### 14.53 温度与 [29](29.llm-sampling-tutorial.md)\n\n封装 **默认 temperature=0.2** RAG；**可 override**。",
        "### 14.54 长上下文\n\n**输入超窗** 封装层 **raise ContextOverflow** **before** 扣费。",
        "### 14.55 多模态（了解）\n\n`chat` 扩展 **image_url** part——[56 多模态](56.multimodal-image-text-tutorial.md)。",
        "### 14.56 练习\n\n实现 `FakeLLMClient` + **pytest** 测 RAGService **无网络**。",
        "### 14.57 生产\n\n**密钥** Vault 注入；**never** print key。",
        "### 14.58 版本 pin\n\n`openai==1.x` **锁版本**；升级 **跑集成测试**。",
        "### 14.59 给团队\n\n「**所有 LLM 调用走 llm/ 包**」——code review **红线**。",
        "### 14.60 收束\n\n**OpenAI 兼容 API 封装** — **167 地基交付**。",
    ),
    "multi-model-routing": _blocks(
        "### 14.30 路由表设计\n\n`primary / fallbacks / max_latency_ms / cost_tier` 四列；**YAML git 管理** + **热加载** feature flag。",
        "### 14.31 任务分类\n\n`rag_answer | summary | rewrite | eval_judge` **不同链**；[100 rewrite](100.query-rewriting-tutorial.md) 用小模型。",
        "### 14.32 健康检查\n\n**每 30s** ping 主模型 **5 token**；**失败** 标记 unhealthy **跳过**。",
        "### 14.33 成本路由\n\n`trial tenant` **强制 small**；**enterprise** 用 **primary**。",
        "### 14.34 延迟路由\n\n**p95 > SLA** 自动 **prefer fast model** **1 小时**。",
        "### 14.35 与 [167](167.openai-api-wrapper-tutorial.md)\n\nRouter **装饰** LLMClient；**metrics** `model_selected`。",
        "### 14.36 与 [163 重试](163.retry-dead-letter-tutorial.md)\n\n**同模型** 重试 **3 次** 后 **才 fallback** **别** 第一次失败就换。",
        "### 14.37 Circuit breaker\n\n**半开** 状态 **试探** primary；**成功** 关闭 breaker。",
        "### 14.38 A/B\n\n[153 AB](153.ab-experiment-rag-tutorial.md) **10% 流量** 新模型 **shadow** 比较 **faithfulness**。",
        "### 14.39 本地 Ollama\n\n`fallback: ollama/llama3` **内网**；**质量** **监控** **降级比例**。",
        "### 14.40 embed 路由禁区\n\n**换 embed model** **必须** 新 collection——Router **拒绝** 不兼容切换。",
        "### 14.41 多 region 路由\n\n**EU tenant** → **EU endpoint** **数据合规**。",
        "### 14.42 面试\n\n「主模型 429？」→ **退避 → fallback → 告警 → 限流协调**。",
        "### 14.43 案例\n\n双 eleven 活动 **429**；**自动 80% 流量** 切 backup **业务无感**。",
        "### 14.44 反模式\n\n**silent fallback** 到 **极弱模型** **无日志**——**用户骂** **不知原因**。",
        "### 14.45 与 [29 采样](29.llm-sampling-tutorial.md)\n\n小模型 **temperature 略升** 补偿。",
        "### 14.46 与 [96 精排](96.bge-reranker-tutorial.md)\n\n**rerank 模型固定** **不** 走路由 **降延迟**。",
        "### 14.47 篇末\n\n**185 多模型路由** — **可用性成本杠杆**。",
        "### 14.48 checklist\n\n- [ ] routing.yaml\n- [ ] breaker\n- [ ] metrics\n- [ ] embed 例外文档",
        "### 14.49 延伸\n\n[167→168→169] **弹性链**。",
        "### 14.50 FinOps 周报\n\n`fallback_rate`、`cost_by_model`、`quality_delta`。",
        "### 14.51 练习\n\nmock primary **429** 测 **fallback 调用顺序**。",
        "### 14.52 配置校验\n\n启动时 **fallback 模型名** **在 provider 存在** **否则 fail fast**。",
        "### 14.53 与 eval\n\n[141 faithfulness](141.ragas-faithfulness-tutorial.md) **对比** primary vs fallback **质量**。",
        "### 14.54 给 SRE\n\n**runbook**：primary 全挂 → **全站 backup** + **降 ingest 优先级**。",
        "### 14.55 多 vendor\n\nOpenAI primary + **DeepSeek backup** **异构** **降** 同故障域。",
        "### 14.56 用户透明\n\n可选 UI **「当前使用快速模式」**——**产品** 决策。",
        "### 14.57 路由测试矩阵\n\nhealthy/unhealthy × task × tier **组合单测**。",
        "### 14.58 与 LangChain\n\n[126 LCEL](126.langchain-lcel-tutorial.md) **可插** RoutingLLM **Runnable**。",
        "### 14.59 死信\n\n**全链失败** → [163 DLQ](163.retry-dead-letter-tutorial.md) **人工重试**。",
        "### 14.60 收束\n\n**多模型路由与降级** — **185 交付**。",
    ),
    "rate-limiting-api": _blocks(
        "### 14.30 限流层次\n\n**CDN/WAF** → **API Gateway** → **应用 middleware** → **LLM Client semaphore** **四层**。",
        "### 14.31 算法选择\n\n**令牌桶** 允许 burst；**漏桶** 平滑；**固定窗口** 简单但有 **边界突发**。",
        "### 14.32 Redis 集群\n\n**Redlock** 或 **单线程 Redis** 保证 **原子**；**Lua 脚本** 减 round-trip。",
        "### 14.33 按 tenant 套餐\n\n[166](166.tenant-isolation-backend-tutorial.md) **quota 表** 驱动 **limit 值**。",
        "### 14.34 按 user 公平\n\n**同一 tenant** 内 **单 user 占 80% TPM** **损害同事**——**per-user 子限**。",
        "### 14.35 ingest 限流\n\n**大文件 embed** **按 MB/min** 限——**防** 打满 **GPU embed 队列**。",
        "### 14.36 与 [168](168.multi-model-routing-tutorial.md)\n\n**429 来自 upstream** **不** 与 **本地 429** 混淆 **error code**。",
        "### 14.37 响应体\n\n```json\n{{\"code\":\"RATE_LIMIT\",\"retry_after\":30,\"limit\":\"60/min\"}}\n```",
        "### 14.38 Retry-After 头\n\n**HTTP 标准**；客户端 [171 UI](171.chat-message-list-ui-tutorial.md) **倒计时** 重试。",
        "### 14.39 白名单\n\n**health check** `/health` **不限**；**internal service** **IP 白名单**。",
        "### 14.40 分布式 race\n\n**滑动窗口** Redis **ZSET** **原子 pipeline**——§6 示例。",
        "### 14.41 面试\n\n「如何防刷 chat？」→ **JWT 身份 + QPS + TPM + 验证码 escalation**。",
        "### 14.42 案例\n\n活动 **10x 流量**；**限流** 保 **SLA** **丢 5% 429** **优于** **全站 5xx**。",
        "### 14.43 与 [169 billing](27.token-counting-billing-tutorial.md)\n\n**超限** **硬停** vs **软告警** **产品** 定。",
        "### 14.44 反模式\n\n**sleep 在 middleware** **阻塞 worker**——**快速 429**。",
        "### 14.45 与 OpenAPI\n\n[170](170.openapi-swagger-docs-tutorial.md) **429 response** 文档化。",
        "### 14.46 监控\n\n`rate_limit_hits` by tenant、path。",
        "### 14.47 篇末\n\n**186 速率限制** — **保护成本与稳定**。",
        "### 14.48 checklist\n\n- [ ] Redis\n- [ ] tenant quota\n- [ ] Retry-After\n- [ ] 压测",
        "### 14.49 延伸\n\n[169→170→171] **客户端体验**。",
        "### 14.50 slowapi 示例\n\n`@limiter.limit(\"60/minute\")` **装饰** 路由 **快速 PoC**。",
        "### 14.51 WebSocket\n\n[117 WS](117.websocket-rag-streaming-tutorial.md) **连接数** 另限。",
        "### 14.52 匿名预览\n\n**未登录** **IP 限** **更严** **5/min**。",
        "### 14.53 与 Celery\n\n**worker 并发** **不是** HTTP 限流 **替代**。",
        "### 14.54 练习\n\nhey 压测 **绘制 429 比例曲线**。",
        "### 14.55 给产品\n\n「排队/稍后再试」**文案** **比** 裸错误 **友好**。",
        "### 14.56 全球\n\n**边缘限流** **减** 跨洋 **无效请求**。",
        "### 14.57 burst 配置\n\n**enterprise burst=100** **trial burst=5**。",
        "### 14.58 与 JWT\n\n**限流 key** 用 **sub** **非** IP（**NAT 公平**）。",
        "### 14.59 日志\n\n**429** **采样 log** **分析** 攻击。",
        "### 14.60 收束\n\n**Rate Limiting** — **API 护城河**。",
    ),
    "openapi-swagger-docs": _blocks(
        "### 14.20 契约驱动开发\n\n**先** openapi.yaml **再** 实现——**或** FastAPI **生成** **commit json** **CI diff**。",
        "### 14.21 版本策略\n\n`/v1/rag/chat` **URL 版本**；**breaking** **升 v2**。",
        "### 14.22 示例值\n\n`Field(examples=[...])` **Swagger 预填** **降** 联调摩擦。",
        "### 14.23 枚举\n\n`ErrorCode` **Literal 枚举** **OpenAPI enum** 自动生成。",
        "### 14.24 SSE 文档\n\nOpenAPI 3.1 **text/event-stream** **或** **单独 markdown** 补充 [116](116.sse-rag-streaming-tutorial.md)。",
        "### 14.25 codegen\n\n`openapi-generator-cli generate -i openapi.json -g typescript-fetch` **给** [171](171.chat-message-list-ui-tutorial.md)。",
        "### 14.26 Mock\n\nPrism / Stoplight **Mock server** **前端 ** 并行。",
        "### 14.27 schemathesis\n\n**fuzz 测试** **发现** 500 **与 schema 漂移**。",
        "### 14.28 与 [164 JWT](164.jwt-auth-rag-tutorial.md)\n\n**Authorize** 按钮 **Bearer** 教程 **截图** onboarding。",
        "### 14.29 与 [165 RBAC](165.rbac-rag-tutorial.md)\n\n**403** **区分** RBAC vs ACL **description** 字段。",
        "### 14.30 生产安全\n\n**/docs 关闭** 或 **Basic Auth**；**json** **artifact** **发内部**。",
        "### 14.31 tags 分组\n\n`auth | rag | admin | ingest` **Swagger 侧边栏清晰**。",
        "### 14.32 面试\n\n「OpenAPI 价值？」→ **契约、Mock、SDK、测试、文档一体**。",
        "### 14.33 反模式\n\n**Postman 集合** **唯一文档** **无 CI** **必腐烂**。",
        "### 14.34 案例\n\n前端 **codegen 类型** **编译期** 发现 **字段改名**。",
        "### 14.35 与 [167](167.openai-api-wrapper-tutorial.md)\n\n**内部 LLMClient** **不** 暴露 OpenAPI——**仅 REST**。",
        "### 14.36 webhook（了解）\n\n**ingest 完成 callback** **optional OpenAPI path**。",
        "### 14.37 篇末\n\n**187 OpenAPI** — **了解但必做 export**。",
        "### 14.38 checklist\n\n- [ ] openapi.json in repo\n- [ ] CI diff\n- [ ] securitySchemes\n- [ ] 401/403/429",
        "### 14.39 延伸\n\n[170→171] **前后端契约**。",
        "### 14.40 Redoc\n\n**只读文档** **给** **外部开发者** **比 Swagger 美观**。",
        "### 14.41 多语言 SDK\n\nPython/TS/Java **同 openapi.json** 生成。",
        "### 14.42 字段 nullable\n\n`str | None` **OpenAPI nullable** **准确** **防** 客户端 **崩溃**。",
        "### 14.43 pagination\n\n`cursor / limit` **标准 query** 文档化。",
        "### 14.44 练习\n\nexport json **import Insomnia** 试 3 端点。",
        "### 14.45 给 PM\n\n「API 文档 **自动跟代码走** **减少** 联调会议。」",
        "### 14.46 deprecated\n\n`deprecated=True` **旧 endpoint** **保留一版**。",
        "### 14.47 servers 块\n\ndev/staging/prod **Swagger 切换**。",
        "### 14.48 与 grpc（了解）\n\n**gRPC 另 proto**；**REST RAG** **OpenAPI 足够**。",
        "### 14.49 一致性\n\n**response_model** **与** 实际 **一致** **integration test**。",
        "### 14.50 收束\n\n**OpenAPI Swagger 文档** — **187 了解篇交付**。",
    ),
    "chat-message-list-ui": _blocks(
        "### 14.30 状态管理选型\n\nPoC **useState**；**多组件** 用 **Zustand**；**服务端历史** **React Query** hydrate。",
        "### 14.31 与 [118 多轮](118.multi-turn-history-tutorial.md)\n\n**messages** 对齐 **OpenAI messages 形状** **便于** debug。",
        "### 14.32 与 [174 流式](174.streaming-typewriter-ui-tutorial.md)\n\n**streaming** 时 **更新 messages 最后一项 content** **+= delta**。",
        "### 14.33 与 [175 Abort](175.abort-controller-stream-tutorial.md)\n\n**AbortController** **取消 fetch** **更新 status=cancelled**。",
        "### 14.34 与 [176 引用](176.citation-card-ui-tutorial.md)\n\n**citations** **Message 子字段** **底部 CardList**。",
        "### 14.35 无障碍\n\n**role=log** **aria-live=polite** **读屏** **新消息**。",
        "### 14.36 虚拟化\n\n**react-virtuoso** **>200 条** **会话** **防 DOM 膨胀**。",
        "### 14.37 主题\n\n**Tailwind** `dark:` **user/assistant** **对比度 WCAG**。",
        "### 14.38 与 [164 JWT](164.jwt-auth-rag-tutorial.md)\n\n**401** **redirect /login**；**token refresh** **silent** **再重发**。",
        "### 14.39 与 [169 429](169.rate-limiting-api-tutorial.md)\n\n**error banner** **显示 retry_after**。",
        "### 14.40 持久化\n\n**sessionStorage** **草稿**；**完整历史** **服务端** [118]。",
        "### 14.41 多会话 sidebar\n\n**conversation_id** **切换** **messages 列表** **清空** **重载**。",
        "### 14.42 面试\n\n「聊天 UI 核心状态？」→ **messages + streaming + error + scroll**。",
        "### 14.43 反模式\n\n**DOM 直接改** **不用 React state** **乱**。",
        "### 14.44 案例\n\n**长表格 answer** **横向 scroll** **bubble max-width**。",
        "### 14.45 与 [172 Markdown](172.markdown-render-rag-tutorial.md)\n\n**AssistantContent** **内嵌 MarkdownRenderer**。",
        "### 14.46 系统消息\n\n**system** **灰条小字** **一般隐藏** **debug 模式显示**。",
        "### 14.47 篇末\n\n**188 聊天 UI** — **G 轨主线**。",
        "### 14.48 checklist\n\n- [ ] Message id uuid\n- [ ] streaming 态\n- [ ] scroll\n- [ ] 401/429",
        "### 14.49 延伸\n\n[171→172→174→176] **前端 RAG 体验链**。",
        "### 14.50 Storybook\n\n**MessageBubble** **stories** **各状态**。",
        "### 14.51 国际化\n\n**时间戳** `Intl.DateTimeFormat`；**RTL** **布局 mirror**。",
        "### 14.52 复制按钮\n\n**assistant** **一键复制** **markdown 源**。",
        "### 14.53 反馈\n\n**👍/👎** **埋点** **评测** [155](155.human-evaluation-rag-tutorial.md)。",
        "### 14.54 练习\n\n加 **「清空对话」** **reset messages**。",
        "### 14.55 给设计\n\n**user 右 assistant 左** **行业惯例** **别反**。",
        "### 14.56 性能\n\n**memo MessageBubble** **props 浅比较**。",
        "### 14.57 SSR\n\n**ChatPage client only** **防 hydration mismatch**。",
        "### 14.58 与 OpenAPI\n\n**类型导入** `@/api/types` **codegen**。",
        "### 14.59 附件（了解）\n\n**user 消息** **带 file chip** [157 upload]。",
        "### 14.60 收束\n\n**聊天消息列表 UI** — **188 主线交付**。",
    ),
    "markdown-render-rag": _blocks(
        "### 14.30 威胁模型详解\n\n**存储型 XSS**：chunk 含 script **经 LLM 复述**；**反射型**：用户输入 **若渲染**；**DOM**：**sanitize 后** **仍禁** innerHTML。",
        "### 14.31 与 [23 Self-Attention](23.self-attention-tutorial.md) 再强调\n\n23 **模型内部** QKV **不可见**；**XSS 是浏览器 DOM**——**培训** **勿混淆** **安全评审**。",
        "### 14.32 CSP 配置\n\n`Content-Security-Policy: default-src 'self'; script-src 'self'` **纵深**。",
        "### 14.33 DOMPurify isomorphic\n\n**SSR** **用 isomorphic-dompurify** **同策略**。",
        "### 14.34 表格与 GFM\n\n**remark-gfm** **表格** **sanitize 允许 table/td/th**。",
        "### 14.35 代码块\n\n**pre/code** **允许**；**属性** **白名单**。",
        "### 14.36 与 [173 高亮](173.code-highlight-rag-tutorial.md)\n\n**shiki** **highlight 消毒后 AST** **节点**。",
        "### 14.37 链接协议\n\n**javascript:** **data:** **拒**；**https 默认**。",
        "### 14.38 图片\n\n**可选禁用 img** **或 CSP img-src** **限域名**。",
        "### 14.39 与 [113 引用](113.inline-citation-tutorial.md)\n\n**CitationSup** **React 组件** **非 HTML 字符串替换**。",
        "### 14.40 与 [171 UI](171.chat-message-list-ui-tutorial.md)\n\n**AssistantContent** **唯一入口** **渲染 LLM 输出**。",
        "### 14.41 测试套件\n\n**OWASP XSS cheat sheet** **前 20 条** **CI**。",
        "### 14.42 面试\n\n「RAG 如何防 XSS？」→ **sanitize + CSP + 禁 raw HTML + 测 LLM 输出**。",
        "### 14.43 反模式\n\n**marked + innerHTML** **默认** **危险**。",
        "### 14.44 案例\n\n**提示注入** 让模型输出 `<img onerror=alert(1)>` **sanitize 剥离**。",
        "### 14.45 用户消息\n\n**user 气泡** **纯 text** **或更严 sanitize** **禁 HTML**。",
        "### 14.46 与 [122 安全](122.content-safety-filter-tutorial.md)\n\n**内容安全** **管有害**；**XSS 管执行** **正交**。",
        "### 14.47 篇末\n\n**189 Markdown 渲染** — **地基必做 sanitize**。",
        "### 14.48 checklist\n\n- [ ] rehype-sanitize\n- [ ] XSS tests\n- [ ] CSP\n- [ ] 禁 dangerouslySetInnerHTML",
        "### 14.49 延伸\n\n[172→173→176] **渲染链**。",
        "### 14.50 mermaid（了解）\n\n**mermaid** **另 sandbox iframe** **禁** 与 markdown **直接混**。",
        "### 14.51 LaTeX（了解）\n\n**KaTeX** **trust: false** **禁 \\htmlRaw**。",
        "### 14.52 复制导出\n\n**下载 markdown** **不** **执行** **仅文本**。",
        "### 14.53 渗透\n\n**安全团队** **扫** **聊天导出 HTML**。",
        "### 14.54 练习\n\n加 **10 条 XSS test case** **Vitest**。",
        "### 14.55 给前端\n\n「**LLM 输出 = 不可信输入**」——**文化** **比工具** **重要**。",
        "### 14.56 与 JWT localStorage\n\n**XSS + localStorage token** **双杀**——[172 sanitize] + [164 HttpOnly] **组合**。",
        "### 14.57 供应链\n\n**react-markdown** **锁版本** **Dependabot**。",
        "### 14.58 日志\n\n**渲染失败** **不** **fallback innerHTML**。",
        "### 14.59 无障碍\n\n**heading 层级** **semantic** **sanitize 保留 h1-h3**。",
        "### 14.60 收束\n\n**Markdown 渲染 RAG** — **189 地基交付**。",
    ),
}
